### ISSUE TITLE
奔溃

### ISSUE THREAD

**Issue by ZQ330093887** [BobEve/Eve#1]
不知道怎么联系你，你的app打开直接奔溃
 Process: bob.eve.walle, PID: 15889
                                                   java.lang.NoClassDefFoundError: bob.eve.mvp.di.component.DaggerAppComponent
                                                       at bob.eve.mvp.base.proxy.ApplicationProxy.onCreate(ApplicationProxy.java:37)
                                                       at bob.eve.walle.app.EveApplication.onCreate(EveApplication.java:52)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4440)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by bobby-walle** [comment]
源码编译安装崩溃？还是使用fir.im安装的？方便说下手机型号和版本么？

**Comment by ZQ330093887** [comment]
HM NOTE 1S 4.4.4
源码编译安装崩溃和还是使用fir.im安装的 都奔溃
